server:
  port: 8003
spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix

#注册到eureka
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://liupeiqing:3bB5ivE8@localhost:8761/eureka
