server:
  port: 8005
spring:
  application:
    name:  microservice-consumer-movie-feign-with-hystrix-stream
eureka:
  instance:
    hostname: feign
   # prefer-ip-address: true  # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整
  client:
    service-url:
      defaultZone:  http://liupeiqing:3bB5ivE8@localhost:8761/eureka
ribbon:
  eureka:
    enabled: true  # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka

                   ### 参考：https://spring.io/guides/gs/client-side-load-balancing/